os: linux
dist: bionic
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
git:
  lfs_skip_smudge: true

before_install:
  - export CC=gcc-8
  - export CXX=g++-8
  - export VKSDK_VERSION=1.2.162.0
  - wget -O ~/vksdk.tar.gz https://sdk.lunarg.com/sdk/download/${VKSDK_VERSION}/linux/vulkansdk-linux-x86_64-${VKSDK_VERSION}.tar.gz
  - mkdir ~/VulkanSDK
  - tar zxf ~/vksdk.tar.gz -C ~/VulkanSDK
  - chmod +x ~/VulkanSDK/${VKSDK_VERSION}/setup-env.sh && source ~/VulkanSDK/${VKSDK_VERSION}/setup-env.sh
  - echo "VULKAN_SDK = ${VULKAN_SDK}"

script:
  - ${CXX} --version
  - chmod +x ./generate.sh
  - chmod +x ./grammar/generate.sh
  - chmod +x ./tools/premake5_l
  - (cd ./grammar && ./generate.sh)
  - ./generate.sh
  - (cd ./build && make config=shared_x64 all)
  - (cd ./build && make config=static_x64 all)
