os: linux
dist: bionic
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
git:
  lfs_skip_smudge: true

before_install:
  - export CC=gcc-8
  - export CXX=g++-8

script:
  - ${CXX} --version
  - chmod +x ./generate.sh
  - chmod +x ./grammar/generate.sh
  - chmod +x ./tools/premake5_l
  - (cd ./grammar && ./generate.sh)
  - ./generate.sh
  - (cd ./build && make -j2 config=shared_x64 all)
  - (cd ./build && make -j2 config=static_x64 all)
